### PR TITLE
Adjusted cpartl, cpartw, cpartinitvegcr for CMT21 for PFT 0,1,2,3 in …

### PR DESCRIPTION
**Pull request by valeriabriones**
…cmt_bgcvegetation

### CODE REVIEW

**Comment by rarutter** [comment]
We're working on branch cleanup - I know there's change to Docker ports that we do not want merged and will deal with that shortly.

**Comment by tobeycarman** [comment]
Maybe we can just make a new branch with only the changes to cmt_bgcvegetation.txt?

**Comment by rarutter** [comment]
Yeah, I could have made a new commit on this branch reversing the changes, but that's messier than rolling back a commit, which then would have to be a new branch and PR. I've isolated the parameter value changes in PR #546

**Comment by tobeycarman** [comment]
Close in favor of #546

**Pull request closed without merging**
